version: '3.8'

services:
  app:
    build: .
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  debug:
    image: busybox
    command: env
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}

volumes:
  mongo-data: